//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PPArticlesEnPanier
{
    public long NoPanier { get; set; }
    public Nullable<long> NoClient { get; set; }
    public Nullable<long> NoVendeur { get; set; }
    public Nullable<long> NoProduit { get; set; }
    public Nullable<System.DateTime> DateCreation { get; set; }
    public Nullable<short> NbItems { get; set; }

    public virtual PPClients PPClients { get; set; }
    public virtual PPProduits PPProduits { get; set; }
    public virtual PPVendeurs PPVendeurs { get; set; }
}

public partial class PPCategories
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPCategories()
    {
        this.PPProduits = new HashSet<PPProduits>();
    }

    public int NoCategorie { get; set; }
    public string Description { get; set; }
    public string Details { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPProduits> PPProduits { get; set; }
}

public partial class PPClients
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPClients()
    {
        this.PPArticlesEnPanier = new HashSet<PPArticlesEnPanier>();
        this.PPCommandes = new HashSet<PPCommandes>();
        this.PPVendeursClients = new HashSet<PPVendeursClients>();
    }

    public long NoClient { get; set; }
    public string AdresseEmail { get; set; }
    public string MotDePasse { get; set; }
    public string Nom { get; set; }
    public string Prenom { get; set; }
    public string Rue { get; set; }
    public string Ville { get; set; }
    public string Province { get; set; }
    public string CodePostal { get; set; }
    public string Pays { get; set; }
    public string Tel1 { get; set; }
    public string Tel2 { get; set; }
    public Nullable<System.DateTime> DateCreation { get; set; }
    public Nullable<System.DateTime> DateMAJ { get; set; }
    public Nullable<short> NbConnexions { get; set; }
    public Nullable<System.DateTime> DateDerniereConnexion { get; set; }
    public Nullable<short> Statut { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPArticlesEnPanier> PPArticlesEnPanier { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPCommandes> PPCommandes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPVendeursClients> PPVendeursClients { get; set; }
}

public partial class PPCommandes
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPCommandes()
    {
        this.PPDetailsCommandes = new HashSet<PPDetailsCommandes>();
    }

    public long NoCommande { get; set; }
    public Nullable<long> NoClient { get; set; }
    public Nullable<long> NoVendeur { get; set; }
    public Nullable<System.DateTime> DateCommande { get; set; }
    public Nullable<decimal> CoutLivraison { get; set; }
    public Nullable<short> TypeLivraison { get; set; }
    public Nullable<decimal> MontantTotAvantTaxes { get; set; }
    public Nullable<decimal> TPS { get; set; }
    public Nullable<decimal> TVQ { get; set; }
    public Nullable<decimal> PoidsTotal { get; set; }
    public string Statut { get; set; }
    public string NoAutorisation { get; set; }

    public virtual PPClients PPClients { get; set; }
    public virtual PPTypesLivraison PPTypesLivraison { get; set; }
    public virtual PPVendeurs PPVendeurs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPDetailsCommandes> PPDetailsCommandes { get; set; }
}

public partial class PPDetailsCommandes
{
    public long NoDetailCommandes { get; set; }
    public Nullable<long> NoCommande { get; set; }
    public Nullable<long> NoProduit { get; set; }
    public Nullable<decimal> PrixVente { get; set; }
    public Nullable<short> Quantité { get; set; }

    public virtual PPCommandes PPCommandes { get; set; }
    public virtual PPProduits PPProduits { get; set; }
}

public partial class PPHistoriquePaiements
{
    public long NoHistorique { get; set; }
    public Nullable<decimal> MontantVenteAvantLivraison { get; set; }
    public Nullable<long> NoVendeur { get; set; }
    public Nullable<long> NoClient { get; set; }
    public Nullable<long> NoCommande { get; set; }
    public Nullable<System.DateTime> DateVente { get; set; }
    public string NoAutorisation { get; set; }
    public Nullable<decimal> FraisLesi { get; set; }
    public Nullable<decimal> Redevance { get; set; }
    public Nullable<decimal> FraisLivraison { get; set; }
    public Nullable<decimal> FraisTPS { get; set; }
    public Nullable<decimal> FraisTVQ { get; set; }
}

public partial class PPPoidsLivraisons
{
    public short CodeLivraison { get; set; }
    public short CodePoids { get; set; }
    public Nullable<decimal> Tarif { get; set; }

    public virtual PPTypesLivraison PPTypesLivraison { get; set; }
    public virtual PPTypesPoids PPTypesPoids { get; set; }
}

public partial class PPProduits
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPProduits()
    {
        this.PPArticlesEnPanier = new HashSet<PPArticlesEnPanier>();
        this.PPDetailsCommandes = new HashSet<PPDetailsCommandes>();
    }

    public long NoProduit { get; set; }
    public Nullable<long> NoVendeur { get; set; }
    public Nullable<int> NoCategorie { get; set; }
    public string Nom { get; set; }
    public string Description { get; set; }
    public string Photo { get; set; }
    public Nullable<decimal> PrixDemande { get; set; }
    public Nullable<short> NombreItems { get; set; }
    public Nullable<bool> Disponibilité { get; set; }
    public Nullable<System.DateTime> DateVente { get; set; }
    public Nullable<decimal> PrixVente { get; set; }
    public Nullable<decimal> Poids { get; set; }
    public Nullable<System.DateTime> DateCreation { get; set; }
    public Nullable<System.DateTime> DateMAJ { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPArticlesEnPanier> PPArticlesEnPanier { get; set; }
    public virtual PPCategories PPCategories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPDetailsCommandes> PPDetailsCommandes { get; set; }
    public virtual PPVendeurs PPVendeurs { get; set; }
}

public partial class PPTaxeFederale
{
    public byte NoTPS { get; set; }
    public Nullable<System.DateTime> DateEffectiveTPS { get; set; }
    public Nullable<decimal> TauxTPS { get; set; }
}

public partial class PPTaxeProvinciale
{
    public byte NoTVQ { get; set; }
    public Nullable<System.DateTime> DateEffectiveTVQ { get; set; }
    public Nullable<decimal> TauxTVQ { get; set; }
}

public partial class PPTypesLivraison
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPTypesLivraison()
    {
        this.PPCommandes = new HashSet<PPCommandes>();
        this.PPPoidsLivraisons = new HashSet<PPPoidsLivraisons>();
    }

    public short CodeLivraison { get; set; }
    public string Description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPCommandes> PPCommandes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPPoidsLivraisons> PPPoidsLivraisons { get; set; }
}

public partial class PPTypesPoids
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPTypesPoids()
    {
        this.PPPoidsLivraisons = new HashSet<PPPoidsLivraisons>();
    }

    public short CodePoids { get; set; }
    public Nullable<decimal> PoidsMin { get; set; }
    public Nullable<decimal> PoidsMax { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPPoidsLivraisons> PPPoidsLivraisons { get; set; }
}

public partial class PPVendeurs
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PPVendeurs()
    {
        this.PPArticlesEnPanier = new HashSet<PPArticlesEnPanier>();
        this.PPCommandes = new HashSet<PPCommandes>();
        this.PPProduits = new HashSet<PPProduits>();
        this.PPVendeursClients = new HashSet<PPVendeursClients>();
    }

    public long NoVendeur { get; set; }
    public string NomAffaires { get; set; }
    public string Nom { get; set; }
    public string Prenom { get; set; }
    public string Rue { get; set; }
    public string Ville { get; set; }
    public string Province { get; set; }
    public string CodePostal { get; set; }
    public string Pays { get; set; }
    public string Tel1 { get; set; }
    public string Tel2 { get; set; }
    public string AdresseEmail { get; set; }
    public string MotDePasse { get; set; }
    public Nullable<int> PoidsMaxLivraison { get; set; }
    public Nullable<decimal> LivraisonGratuite { get; set; }
    public Nullable<bool> Taxes { get; set; }
    public Nullable<decimal> Pourcentage { get; set; }
    public string Configuration { get; set; }
    public Nullable<System.DateTime> DateCreation { get; set; }
    public Nullable<System.DateTime> DateMAJ { get; set; }
    public Nullable<short> Statut { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPArticlesEnPanier> PPArticlesEnPanier { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPCommandes> PPCommandes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPProduits> PPProduits { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PPVendeursClients> PPVendeursClients { get; set; }
}

public partial class PPVendeursClients
{
    public long NoVendeur { get; set; }
    public long NoClient { get; set; }
    public System.DateTime DateVisite { get; set; }

    public virtual PPClients PPClients { get; set; }
    public virtual PPVendeurs PPVendeurs { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
