//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class BD6B8_424SEntities : DbContext
{
    public BD6B8_424SEntities()
        : base("name=BD6B8_424SEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<PPArticlesEnPanier> PPArticlesEnPanier { get; set; }
    public virtual DbSet<PPCategories> PPCategories { get; set; }
    public virtual DbSet<PPClients> PPClients { get; set; }
    public virtual DbSet<PPCommandes> PPCommandes { get; set; }
    public virtual DbSet<PPDetailsCommandes> PPDetailsCommandes { get; set; }
    public virtual DbSet<PPHistoriquePaiements> PPHistoriquePaiements { get; set; }
    public virtual DbSet<PPPoidsLivraisons> PPPoidsLivraisons { get; set; }
    public virtual DbSet<PPProduits> PPProduits { get; set; }
    public virtual DbSet<PPTaxeFederale> PPTaxeFederale { get; set; }
    public virtual DbSet<PPTaxeProvinciale> PPTaxeProvinciale { get; set; }
    public virtual DbSet<PPTypesLivraison> PPTypesLivraison { get; set; }
    public virtual DbSet<PPTypesPoids> PPTypesPoids { get; set; }
    public virtual DbSet<PPVendeurs> PPVendeurs { get; set; }
    public virtual DbSet<PPVendeursClients> PPVendeursClients { get; set; }
    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
}
